// The first line of every generated file. CI fails if generated/ is not what
// `pnpm render` produces, so a hand edit there is always caught and reverted.
export function HEADER(comment: string): string {
  return `${comment} GENERATED by \`pnpm render\` from sites.yaml. Do not edit by hand; edit sites.yaml and re-render.\n`
}
